#.travis.yml

language: node_js
node_js:
  - "8.11.1"

branches:
  only:
    - master
    - v2
    - v3-Routing
    - v4-Comments
    - v5-PWA

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod
  - npm run precache

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
    